### ISSUE TITLE
Technical names on page load and slashcommands not working on some instances

### ISSUE THREAD

**Issue by CBacchus** [arnoudkooi/ServiceNow-Utils#523] opened 2024-07-02 14:38 UTC
We have several instances, most are on glide-vancouver-07-06-2023__patch7-hotfix3b-05-23-2024. One instance is on glide-vancouver-07-06-2023__patch9-05-02-2024. The instance on patch 9 appears to work perfectly fine. The instances on patch 7, however, do not load technical names on page load, and the slashcommands popup will not appear. I can get the technical names to show when double clicking on the page. I noticed in the console on the patch 7 instances that there is an error, and I believe it is the cause for these features to not work. I've attached a screenshot of the console with the error. 

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/1498100/eea91bcc-34d5-4d1d-88cf-685c2599a3aa)

**Comment by arnoudkooi** [comment] 2024-07-02 14:53
Are you on Next Experience?

**Comment by arnoudkooi** [comment] 2024-07-03 07:10
Can you update and check if the issue is solved?

**Comment by arnoudkooi** [comment] 2024-07-03 14:32
Could you debug the snuLoarTheneVariablesFunction to see where it exits? Otherwise we should plan a call

**Comment by arnoudkooi** [comment] 2024-07-03 16:20
I could check in, are you available?

**Comment by arnoudkooi** [comment] 2024-07-03 16:29
https://servicenow.zoom.us/my/arnoudkooi

**Comment by arnoudkooi** [comment] 2024-07-03 17:41
There was a polyfill for Promises in use on the instance that did not support the finally call.
Removed the use of the finally call.
Will stay in touch to see if it is fixed once 8.1.5.7 is rolled out

**Comment by arnoudkooi** [comment] 2024-07-03 19:58
This time the OnPrem was published first, could you check and let me know?

**Closed as completed** 2024-07-05 14:10 UTC
