### ISSUE TITLE
SN Utils runs forever in BackgroundScript

### ISSUE THREAD

**Issue by iCode18** [arnoudkooi/ServiceNow-Utils#475] opened 2024-02-20 06:25 UTC
Anybody know how to fix SN Utils BG in Washington, mine is weird after the upgrade as shown in the screenshot
it missed the VS code theme and functionality and even though a smal test like gs.info("Hello SN"); runs none-stop.
Sorry if this is asked before but I did not found link or solution.

**Comment by arnoudkooi** [comment] 2024-02-20 06:51
Not seeing a screenshot....

**Comment by iCode18** [comment] 2024-02-20 07:11
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/24635602/7ea42615-d300-485b-bc36-24284682b65d)

**Comment by arnoudkooi** [comment] 2024-02-20 07:15
can you check console for error?

**Comment by iCode18** [comment] 2024-02-20 07:23
Initializing Database!
857e62d76f2b764061f06ea22e3ee491.cssdbx:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
SweetAlerts2-min.jsdbx:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
sys.scripts.modern.do:482 Uncaught SyntaxError: Unexpected identifier 'minHeight'
xperf_timing.jsx?v=02-02-2024_1052:12 +-- Parse times
xperf_timing.jsx?v=02-02-2024_1052:13 | CSS parse: 47.599999994039536
xperf_timing.jsx?v=02-02-2024_1052:14 | JS  doctype: 147.80000000447035
xperf_timing.jsx?v=02-02-2024_1052:15 | JS at end of page: 10.400000005960464
xperf_timing.jsx?v=02-02-2024_1052:16 +-- All parsing: 205.80000000447035
js_includes_amb.jsx?v=02-02-2024_1052&lp=Sun_Feb_18_11_49_57_PST_2024&c=33_965:2 amb.ServerConnection [INFO] _initializeSubscriptionCommandSender: SubscriptionCommandSender is enabled
js_includes_amb.jsx?v=02-02-2024_1052&lp=Sun_Feb_18_11_49_57_PST_2024&c=33_965:2 amb.TransportManagement [INFO] Connected using transport websocket
js_includes_amb.jsx?v=02-02-2024_1052&lp=Sun_Feb_18_11_49_57_PST_2024&c=33_965:2 amb.TransportManagement [INFO] Removed failed registry transports after connect: {}
bgscriptmodern.js:142 Uncaught TypeError: Cannot read properties of undefined (reading 'addAction')
    at snuEnhanceMonaco (bgscriptmodern.js:142:9)
    at bgscriptmodern.js:24:2
857e62d76f2b764061f06ea22e3ee491.cssdbx:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by iCode18** [comment] 2024-02-20 07:23
![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/24635602/87219755-36c9-463f-9e47-9ef6f406bf52)

**Comment by arnoudkooi** [comment] 2024-02-20 08:32
Could you run the below in console and share the result (screenshot)?

```javascript
console.log(window.monaco.editor.getEditors()[0]);
console.log(GlideEditorMonaco.get('script').editor);
```

**Comment by iCode18** [comment] 2024-02-20 09:54
> Could you run the below in console and share the result (screenshot)?
> 
> ```js
> console.log(window.monaco.editor.getEditors()[0]);
> console.log(GlideEditorMonaco.get('script').editor);
> ```

![image](https://github.com/arnoudkooi/ServiceNow-Utils/assets/24635602/39c581c3-c266-491f-8086-0b3fe40e16e7)

**Comment by arnoudkooi** [comment] 2024-02-20 09:59
do you have a few minutes to check in? Ill join now
https://servicenow.zoom.us/my/arnoudkooi

**Comment by arnoudkooi** [comment] 2024-02-20 11:12
This seems to be an instance related problem, as the Monaco editor does not get applied, even when you disable SN Utils. I recommend logging a support case.

I'll leave it open please update when you know more.

**Comment by iCode18** [comment] 2024-03-01 07:10
Some updates from ServiceNow:
When we set the glide.ui.syntax_editor.polaris=false, it switches the script editor from Monaco Editor to CodeMirror. Unfortunately, the code editor toolbar on sys.scripts.modern.do does not work with CodeMirror.

Setting glide.ui.syntax_editor.polaris=true will switch the script editor back to Monaco Editor and the code editor toolbar will work properly on sys.script.modern.do.

There is an issue with Jelly code not handling escape characters properly on this instance and dev team is working on fixing the same. I will keep you posted further once its fixed.

**Comment by iCode18** [comment] 2024-03-05 08:20
ServiceNow dev team added a new record to sys_ui_macro
This new record is a macro and it is replacing double quotes by single quotes on editor_monaco_init_script.xml to fix missing escape characters due to missing JS prefix as mentioned on
https://docs.servicenow.com/bundle/washingtondc-api-reference/page/script/server-scripting/reference/r_JellyEscapingTypes.html

This fixed everything so far except the VS code theme.

**Comment by arnoudkooi** [comment] 2024-03-08 23:05
As this is confirmed to be an instance issue, Im closing this. Thanks for the updates and feel free to add solution when it is fixed.

**Closed by arnoudkooi** 2024-03-08 23:05 UTC
