### ISSUE TITLE
Invalid link for 'New Updateset' 

### ISSUE THREAD

**Issue by jsmayo** [arnoudkooi/ServiceNow-Utils#393] opened 2023-05-04 15:23 UTC
Clicking the 'New updateset' link opens a tab with the url pointing to: chrome-extension://jgaodbdddndbaijmcljdbglhpdhnjobg/popup.html

**Comment by jsmayo** [comment] 2023-05-05 02:24
I'll need to wait until tomorrow so that I can try again on my work
computer. The extension works fine for instances that have the generic '
instName.service-now.com' domain. However, I made sure that I was using the
*alternate* version since our instance uses a different domain and while
some functionality does work as intended I've noticed that the 'new
updateset' link at the bottom of the Update Set tab continually opens a new
browser tab with what's typically shown in the extension's "About" tab. The
same behavior can be seen when using the 'create updateset' link on a *non*
service-now domain (e.g google.com), so I was wondering if there was some
conditional logic potentially missing in the extension for this specific
link. Again, this is for the alternate version that supports instances not
on the service-now domain.

Aside from that, I've used your extension for going on 4 to 5 years
(recently needed the alternate version) and just wanted to say that you're
doing an awesome job and to thank you for all the hard work and dedication
:)!!

Thanks so much :D,

*Jesse Mayo*

**Comment by arnoudkooi** [comment] 2023-05-13 19:10
So far I was not able to reproduce this issue.
When it occurs, could you inspect the popup and see if there are console errors?
Also maybe chack the value of the url variable.
![Google Chrome20230513 - 2109](https://github.com/arnoudkooi/ServiceNow-Utils/assets/840781/7e935fcf-2a9b-4018-ac95-bf340c039dac)

**Comment by arnoudkooi** [comment] 2023-05-16 23:00
I will look at it when you have steps to reproduce. Closing it for now

**Closed by arnoudkooi** 2023-05-16 23:00 UTC

**Comment by jsmayo** [comment] 2023-05-18 02:19
https://a.cl.ly/4guN6GGL

Thanks,

*Jesse Mayo*
